#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWEprotein.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DBSweProtein")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttbOrder(tbOrder instance);
    partial void UpdatetbOrder(tbOrder instance);
    partial void DeletetbOrder(tbOrder instance);
    partial void InserttbUser(tbUser instance);
    partial void UpdatetbUser(tbUser instance);
    partial void DeletetbUser(tbUser instance);
    partial void InserttbProduct(tbProduct instance);
    partial void UpdatetbProduct(tbProduct instance);
    partial void DeletetbProduct(tbProduct instance);
    partial void InserttbProductCategory(tbProductCategory instance);
    partial void UpdatetbProductCategory(tbProductCategory instance);
    partial void DeletetbProductCategory(tbProductCategory instance);
    partial void InserttbProductOrder(tbProductOrder instance);
    partial void UpdatetbProductOrder(tbProductOrder instance);
    partial void DeletetbProductOrder(tbProductOrder instance);
    partial void InserttbProductType(tbProductType instance);
    partial void UpdatetbProductType(tbProductType instance);
    partial void DeletetbProductType(tbProductType instance);
    partial void InserttbRole(tbRole instance);
    partial void UpdatetbRole(tbRole instance);
    partial void DeletetbRole(tbRole instance);
    partial void InserttbShippingInfo(tbShippingInfo instance);
    partial void UpdatetbShippingInfo(tbShippingInfo instance);
    partial void DeletetbShippingInfo(tbShippingInfo instance);
    partial void InserttbStatus(tbStatus instance);
    partial void UpdatetbStatus(tbStatus instance);
    partial void DeletetbStatus(tbStatus instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DBSweProteinConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbOrder> tbOrders
		{
			get
			{
				return this.GetTable<tbOrder>();
			}
		}
		
		public System.Data.Linq.Table<tbUser> tbUsers
		{
			get
			{
				return this.GetTable<tbUser>();
			}
		}
		
		public System.Data.Linq.Table<tbProduct> tbProducts
		{
			get
			{
				return this.GetTable<tbProduct>();
			}
		}
		
		public System.Data.Linq.Table<tbProductCategory> tbProductCategories
		{
			get
			{
				return this.GetTable<tbProductCategory>();
			}
		}
		
		public System.Data.Linq.Table<tbProductOrder> tbProductOrders
		{
			get
			{
				return this.GetTable<tbProductOrder>();
			}
		}
		
		public System.Data.Linq.Table<tbProductType> tbProductTypes
		{
			get
			{
				return this.GetTable<tbProductType>();
			}
		}
		
		public System.Data.Linq.Table<tbRole> tbRoles
		{
			get
			{
				return this.GetTable<tbRole>();
			}
		}
		
		public System.Data.Linq.Table<tbShippingInfo> tbShippingInfos
		{
			get
			{
				return this.GetTable<tbShippingInfo>();
			}
		}
		
		public System.Data.Linq.Table<tbStatus> tbStatus
		{
			get
			{
				return this.GetTable<tbStatus>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbOrder")]
	public partial class tbOrder : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _iID;
		
		private int _iUserID;
		
		private int _iStatus;
		
		private System.Nullable<int> _iSum;
		
		private System.Nullable<System.DateTime> _dtOrderDate;
		
		private EntitySet<tbProductOrder> _tbProductOrders;
		
		private EntityRef<tbUser> _tbUser;
		
		private EntityRef<tbStatus> _tbStatus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OniIDChanging(int value);
    partial void OniIDChanged();
    partial void OniUserIDChanging(int value);
    partial void OniUserIDChanged();
    partial void OniStatusChanging(int value);
    partial void OniStatusChanged();
    partial void OniSumChanging(System.Nullable<int> value);
    partial void OniSumChanged();
    partial void OndtOrderDateChanging(System.Nullable<System.DateTime> value);
    partial void OndtOrderDateChanged();
    #endregion
		
		public tbOrder()
		{
			this._tbProductOrders = new EntitySet<tbProductOrder>(new Action<tbProductOrder>(this.attach_tbProductOrders), new Action<tbProductOrder>(this.detach_tbProductOrders));
			this._tbUser = default(EntityRef<tbUser>);
			this._tbStatus = default(EntityRef<tbStatus>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int iID
		{
			get
			{
				return this._iID;
			}
			set
			{
				if ((this._iID != value))
				{
					this.OniIDChanging(value);
					this.SendPropertyChanging();
					this._iID = value;
					this.SendPropertyChanged("iID");
					this.OniIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iUserID", DbType="Int NOT NULL")]
		public int iUserID
		{
			get
			{
				return this._iUserID;
			}
			set
			{
				if ((this._iUserID != value))
				{
					if (this._tbUser.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OniUserIDChanging(value);
					this.SendPropertyChanging();
					this._iUserID = value;
					this.SendPropertyChanged("iUserID");
					this.OniUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iStatus", DbType="Int NOT NULL")]
		public int iStatus
		{
			get
			{
				return this._iStatus;
			}
			set
			{
				if ((this._iStatus != value))
				{
					if (this._tbStatus.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OniStatusChanging(value);
					this.SendPropertyChanging();
					this._iStatus = value;
					this.SendPropertyChanged("iStatus");
					this.OniStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iSum", DbType="Int")]
		public System.Nullable<int> iSum
		{
			get
			{
				return this._iSum;
			}
			set
			{
				if ((this._iSum != value))
				{
					this.OniSumChanging(value);
					this.SendPropertyChanging();
					this._iSum = value;
					this.SendPropertyChanged("iSum");
					this.OniSumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtOrderDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> dtOrderDate
		{
			get
			{
				return this._dtOrderDate;
			}
			set
			{
				if ((this._dtOrderDate != value))
				{
					this.OndtOrderDateChanging(value);
					this.SendPropertyChanging();
					this._dtOrderDate = value;
					this.SendPropertyChanged("dtOrderDate");
					this.OndtOrderDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbOrder_tbProductOrder", Storage="_tbProductOrders", ThisKey="iID", OtherKey="iOrderID")]
		public EntitySet<tbProductOrder> tbProductOrders
		{
			get
			{
				return this._tbProductOrders;
			}
			set
			{
				this._tbProductOrders.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbUser_tbOrder", Storage="_tbUser", ThisKey="iUserID", OtherKey="iID", IsForeignKey=true)]
		public tbUser tbUser
		{
			get
			{
				return this._tbUser.Entity;
			}
			set
			{
				tbUser previousValue = this._tbUser.Entity;
				if (((previousValue != value) 
							|| (this._tbUser.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbUser.Entity = null;
						previousValue.tbOrders.Remove(this);
					}
					this._tbUser.Entity = value;
					if ((value != null))
					{
						value.tbOrders.Add(this);
						this._iUserID = value.iID;
					}
					else
					{
						this._iUserID = default(int);
					}
					this.SendPropertyChanged("tbUser");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbStatus_tbOrder", Storage="_tbStatus", ThisKey="iStatus", OtherKey="iID", IsForeignKey=true)]
		public tbStatus tbStatus
		{
			get
			{
				return this._tbStatus.Entity;
			}
			set
			{
				tbStatus previousValue = this._tbStatus.Entity;
				if (((previousValue != value) 
							|| (this._tbStatus.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbStatus.Entity = null;
						previousValue.tbOrders.Remove(this);
					}
					this._tbStatus.Entity = value;
					if ((value != null))
					{
						value.tbOrders.Add(this);
						this._iStatus = value.iID;
					}
					else
					{
						this._iStatus = default(int);
					}
					this.SendPropertyChanged("tbStatus");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbProductOrders(tbProductOrder entity)
		{
			this.SendPropertyChanging();
			entity.tbOrder = this;
		}
		
		private void detach_tbProductOrders(tbProductOrder entity)
		{
			this.SendPropertyChanging();
			entity.tbOrder = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbUser")]
	public partial class tbUser : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _iID;
		
		private int _iRole;
		
		private int _iShippingInfo;
		
		private string _sUsername;
		
		private string _sPassword;
		
		private string _sEmail;
		
		private string _sTelephone;
		
		private System.Nullable<int> _iTotalPurchase;
		
		private EntitySet<tbOrder> _tbOrders;
		
		private EntityRef<tbRole> _tbRole;
		
		private EntityRef<tbShippingInfo> _tbShippingInfo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OniIDChanging(int value);
    partial void OniIDChanged();
    partial void OniRoleChanging(int value);
    partial void OniRoleChanged();
    partial void OniShippingInfoChanging(int value);
    partial void OniShippingInfoChanged();
    partial void OnsUsernameChanging(string value);
    partial void OnsUsernameChanged();
    partial void OnsPasswordChanging(string value);
    partial void OnsPasswordChanged();
    partial void OnsEmailChanging(string value);
    partial void OnsEmailChanged();
    partial void OnsTelephoneChanging(string value);
    partial void OnsTelephoneChanged();
    partial void OniTotalPurchaseChanging(System.Nullable<int> value);
    partial void OniTotalPurchaseChanged();
    #endregion
		
		public tbUser()
		{
			this._tbOrders = new EntitySet<tbOrder>(new Action<tbOrder>(this.attach_tbOrders), new Action<tbOrder>(this.detach_tbOrders));
			this._tbRole = default(EntityRef<tbRole>);
			this._tbShippingInfo = default(EntityRef<tbShippingInfo>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int iID
		{
			get
			{
				return this._iID;
			}
			set
			{
				if ((this._iID != value))
				{
					this.OniIDChanging(value);
					this.SendPropertyChanging();
					this._iID = value;
					this.SendPropertyChanged("iID");
					this.OniIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iRole", DbType="Int NOT NULL")]
		public int iRole
		{
			get
			{
				return this._iRole;
			}
			set
			{
				if ((this._iRole != value))
				{
					if (this._tbRole.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OniRoleChanging(value);
					this.SendPropertyChanging();
					this._iRole = value;
					this.SendPropertyChanged("iRole");
					this.OniRoleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iShippingInfo", DbType="Int NOT NULL")]
		public int iShippingInfo
		{
			get
			{
				return this._iShippingInfo;
			}
			set
			{
				if ((this._iShippingInfo != value))
				{
					if (this._tbShippingInfo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OniShippingInfoChanging(value);
					this.SendPropertyChanging();
					this._iShippingInfo = value;
					this.SendPropertyChanged("iShippingInfo");
					this.OniShippingInfoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sUsername", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string sUsername
		{
			get
			{
				return this._sUsername;
			}
			set
			{
				if ((this._sUsername != value))
				{
					this.OnsUsernameChanging(value);
					this.SendPropertyChanging();
					this._sUsername = value;
					this.SendPropertyChanged("sUsername");
					this.OnsUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sPassword", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string sPassword
		{
			get
			{
				return this._sPassword;
			}
			set
			{
				if ((this._sPassword != value))
				{
					this.OnsPasswordChanging(value);
					this.SendPropertyChanging();
					this._sPassword = value;
					this.SendPropertyChanged("sPassword");
					this.OnsPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sEmail", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string sEmail
		{
			get
			{
				return this._sEmail;
			}
			set
			{
				if ((this._sEmail != value))
				{
					this.OnsEmailChanging(value);
					this.SendPropertyChanging();
					this._sEmail = value;
					this.SendPropertyChanged("sEmail");
					this.OnsEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sTelephone", DbType="NVarChar(50)")]
		public string sTelephone
		{
			get
			{
				return this._sTelephone;
			}
			set
			{
				if ((this._sTelephone != value))
				{
					this.OnsTelephoneChanging(value);
					this.SendPropertyChanging();
					this._sTelephone = value;
					this.SendPropertyChanged("sTelephone");
					this.OnsTelephoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iTotalPurchase", DbType="Int")]
		public System.Nullable<int> iTotalPurchase
		{
			get
			{
				return this._iTotalPurchase;
			}
			set
			{
				if ((this._iTotalPurchase != value))
				{
					this.OniTotalPurchaseChanging(value);
					this.SendPropertyChanging();
					this._iTotalPurchase = value;
					this.SendPropertyChanged("iTotalPurchase");
					this.OniTotalPurchaseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbUser_tbOrder", Storage="_tbOrders", ThisKey="iID", OtherKey="iUserID")]
		public EntitySet<tbOrder> tbOrders
		{
			get
			{
				return this._tbOrders;
			}
			set
			{
				this._tbOrders.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbRole_tbUser", Storage="_tbRole", ThisKey="iRole", OtherKey="iID", IsForeignKey=true)]
		public tbRole tbRole
		{
			get
			{
				return this._tbRole.Entity;
			}
			set
			{
				tbRole previousValue = this._tbRole.Entity;
				if (((previousValue != value) 
							|| (this._tbRole.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbRole.Entity = null;
						previousValue.tbUsers.Remove(this);
					}
					this._tbRole.Entity = value;
					if ((value != null))
					{
						value.tbUsers.Add(this);
						this._iRole = value.iID;
					}
					else
					{
						this._iRole = default(int);
					}
					this.SendPropertyChanged("tbRole");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbShippingInfo_tbUser", Storage="_tbShippingInfo", ThisKey="iShippingInfo", OtherKey="iID", IsForeignKey=true)]
		public tbShippingInfo tbShippingInfo
		{
			get
			{
				return this._tbShippingInfo.Entity;
			}
			set
			{
				tbShippingInfo previousValue = this._tbShippingInfo.Entity;
				if (((previousValue != value) 
							|| (this._tbShippingInfo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbShippingInfo.Entity = null;
						previousValue.tbUsers.Remove(this);
					}
					this._tbShippingInfo.Entity = value;
					if ((value != null))
					{
						value.tbUsers.Add(this);
						this._iShippingInfo = value.iID;
					}
					else
					{
						this._iShippingInfo = default(int);
					}
					this.SendPropertyChanged("tbShippingInfo");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbOrders(tbOrder entity)
		{
			this.SendPropertyChanging();
			entity.tbUser = this;
		}
		
		private void detach_tbOrders(tbOrder entity)
		{
			this.SendPropertyChanging();
			entity.tbUser = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbProduct")]
	public partial class tbProduct : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _iID;
		
		private int _iProductType;
		
		private string _sName;
		
		private int _iPrice;
		
		private string _sPicture;
		
		private string _sDescription;
		
		private int _iStockBalance;
		
		private int _iItemsSold;
		
		private int _iCount;
		
		private EntitySet<tbProductOrder> _tbProductOrders;
		
		private EntityRef<tbProductType> _tbProductType;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OniIDChanging(int value);
    partial void OniIDChanged();
    partial void OniProductTypeChanging(int value);
    partial void OniProductTypeChanged();
    partial void OnsNameChanging(string value);
    partial void OnsNameChanged();
    partial void OniPriceChanging(int value);
    partial void OniPriceChanged();
    partial void OnsPictureChanging(string value);
    partial void OnsPictureChanged();
    partial void OnsDescriptionChanging(string value);
    partial void OnsDescriptionChanged();
    partial void OniStockBalanceChanging(int value);
    partial void OniStockBalanceChanged();
    partial void OniItemsSoldChanging(int value);
    partial void OniItemsSoldChanged();
    partial void OniCountChanging(int value);
    partial void OniCountChanged();
    #endregion
		
		public tbProduct()
		{
			this._tbProductOrders = new EntitySet<tbProductOrder>(new Action<tbProductOrder>(this.attach_tbProductOrders), new Action<tbProductOrder>(this.detach_tbProductOrders));
			this._tbProductType = default(EntityRef<tbProductType>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int iID
		{
			get
			{
				return this._iID;
			}
			set
			{
				if ((this._iID != value))
				{
					this.OniIDChanging(value);
					this.SendPropertyChanging();
					this._iID = value;
					this.SendPropertyChanged("iID");
					this.OniIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iProductType", DbType="Int NOT NULL")]
		public int iProductType
		{
			get
			{
				return this._iProductType;
			}
			set
			{
				if ((this._iProductType != value))
				{
					if (this._tbProductType.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OniProductTypeChanging(value);
					this.SendPropertyChanging();
					this._iProductType = value;
					this.SendPropertyChanged("iProductType");
					this.OniProductTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string sName
		{
			get
			{
				return this._sName;
			}
			set
			{
				if ((this._sName != value))
				{
					this.OnsNameChanging(value);
					this.SendPropertyChanging();
					this._sName = value;
					this.SendPropertyChanged("sName");
					this.OnsNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iPrice", DbType="Int NOT NULL")]
		public int iPrice
		{
			get
			{
				return this._iPrice;
			}
			set
			{
				if ((this._iPrice != value))
				{
					this.OniPriceChanging(value);
					this.SendPropertyChanging();
					this._iPrice = value;
					this.SendPropertyChanged("iPrice");
					this.OniPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sPicture", DbType="NVarChar(200)")]
		public string sPicture
		{
			get
			{
				return this._sPicture;
			}
			set
			{
				if ((this._sPicture != value))
				{
					this.OnsPictureChanging(value);
					this.SendPropertyChanging();
					this._sPicture = value;
					this.SendPropertyChanged("sPicture");
					this.OnsPictureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sDescription", DbType="NVarChar(2000)")]
		public string sDescription
		{
			get
			{
				return this._sDescription;
			}
			set
			{
				if ((this._sDescription != value))
				{
					this.OnsDescriptionChanging(value);
					this.SendPropertyChanging();
					this._sDescription = value;
					this.SendPropertyChanged("sDescription");
					this.OnsDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iStockBalance", DbType="Int NOT NULL")]
		public int iStockBalance
		{
			get
			{
				return this._iStockBalance;
			}
			set
			{
				if ((this._iStockBalance != value))
				{
					this.OniStockBalanceChanging(value);
					this.SendPropertyChanging();
					this._iStockBalance = value;
					this.SendPropertyChanged("iStockBalance");
					this.OniStockBalanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iItemsSold", DbType="Int NOT NULL")]
		public int iItemsSold
		{
			get
			{
				return this._iItemsSold;
			}
			set
			{
				if ((this._iItemsSold != value))
				{
					this.OniItemsSoldChanging(value);
					this.SendPropertyChanging();
					this._iItemsSold = value;
					this.SendPropertyChanged("iItemsSold");
					this.OniItemsSoldChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iCount", DbType="Int NOT NULL")]
		public int iCount
		{
			get
			{
				return this._iCount;
			}
			set
			{
				if ((this._iCount != value))
				{
					this.OniCountChanging(value);
					this.SendPropertyChanging();
					this._iCount = value;
					this.SendPropertyChanged("iCount");
					this.OniCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbProduct_tbProductOrder", Storage="_tbProductOrders", ThisKey="iID", OtherKey="iProductID")]
		public EntitySet<tbProductOrder> tbProductOrders
		{
			get
			{
				return this._tbProductOrders;
			}
			set
			{
				this._tbProductOrders.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbProductType_tbProduct", Storage="_tbProductType", ThisKey="iProductType", OtherKey="iID", IsForeignKey=true)]
		public tbProductType tbProductType
		{
			get
			{
				return this._tbProductType.Entity;
			}
			set
			{
				tbProductType previousValue = this._tbProductType.Entity;
				if (((previousValue != value) 
							|| (this._tbProductType.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbProductType.Entity = null;
						previousValue.tbProducts.Remove(this);
					}
					this._tbProductType.Entity = value;
					if ((value != null))
					{
						value.tbProducts.Add(this);
						this._iProductType = value.iID;
					}
					else
					{
						this._iProductType = default(int);
					}
					this.SendPropertyChanged("tbProductType");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbProductOrders(tbProductOrder entity)
		{
			this.SendPropertyChanging();
			entity.tbProduct = this;
		}
		
		private void detach_tbProductOrders(tbProductOrder entity)
		{
			this.SendPropertyChanging();
			entity.tbProduct = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbProductCategory")]
	public partial class tbProductCategory : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _iID;
		
		private string _sName;
		
		private EntitySet<tbProductType> _tbProductTypes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OniIDChanging(int value);
    partial void OniIDChanged();
    partial void OnsNameChanging(string value);
    partial void OnsNameChanged();
    #endregion
		
		public tbProductCategory()
		{
			this._tbProductTypes = new EntitySet<tbProductType>(new Action<tbProductType>(this.attach_tbProductTypes), new Action<tbProductType>(this.detach_tbProductTypes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int iID
		{
			get
			{
				return this._iID;
			}
			set
			{
				if ((this._iID != value))
				{
					this.OniIDChanging(value);
					this.SendPropertyChanging();
					this._iID = value;
					this.SendPropertyChanged("iID");
					this.OniIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string sName
		{
			get
			{
				return this._sName;
			}
			set
			{
				if ((this._sName != value))
				{
					this.OnsNameChanging(value);
					this.SendPropertyChanging();
					this._sName = value;
					this.SendPropertyChanged("sName");
					this.OnsNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbProductCategory_tbProductType", Storage="_tbProductTypes", ThisKey="iID", OtherKey="iProductCategory")]
		public EntitySet<tbProductType> tbProductTypes
		{
			get
			{
				return this._tbProductTypes;
			}
			set
			{
				this._tbProductTypes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbProductTypes(tbProductType entity)
		{
			this.SendPropertyChanging();
			entity.tbProductCategory = this;
		}
		
		private void detach_tbProductTypes(tbProductType entity)
		{
			this.SendPropertyChanging();
			entity.tbProductCategory = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbProductOrder")]
	public partial class tbProductOrder : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _iID;
		
		private int _iOrderID;
		
		private int _iProductID;
		
		private int _iQuantity;
		
		private System.Nullable<int> _iPrice;
		
		private EntityRef<tbOrder> _tbOrder;
		
		private EntityRef<tbProduct> _tbProduct;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OniIDChanging(int value);
    partial void OniIDChanged();
    partial void OniOrderIDChanging(int value);
    partial void OniOrderIDChanged();
    partial void OniProductIDChanging(int value);
    partial void OniProductIDChanged();
    partial void OniQuantityChanging(int value);
    partial void OniQuantityChanged();
    partial void OniPriceChanging(System.Nullable<int> value);
    partial void OniPriceChanged();
    #endregion
		
		public tbProductOrder()
		{
			this._tbOrder = default(EntityRef<tbOrder>);
			this._tbProduct = default(EntityRef<tbProduct>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int iID
		{
			get
			{
				return this._iID;
			}
			set
			{
				if ((this._iID != value))
				{
					this.OniIDChanging(value);
					this.SendPropertyChanging();
					this._iID = value;
					this.SendPropertyChanged("iID");
					this.OniIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iOrderID", DbType="Int NOT NULL")]
		public int iOrderID
		{
			get
			{
				return this._iOrderID;
			}
			set
			{
				if ((this._iOrderID != value))
				{
					if (this._tbOrder.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OniOrderIDChanging(value);
					this.SendPropertyChanging();
					this._iOrderID = value;
					this.SendPropertyChanged("iOrderID");
					this.OniOrderIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iProductID", DbType="Int NOT NULL")]
		public int iProductID
		{
			get
			{
				return this._iProductID;
			}
			set
			{
				if ((this._iProductID != value))
				{
					if (this._tbProduct.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OniProductIDChanging(value);
					this.SendPropertyChanging();
					this._iProductID = value;
					this.SendPropertyChanged("iProductID");
					this.OniProductIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iQuantity", DbType="Int NOT NULL")]
		public int iQuantity
		{
			get
			{
				return this._iQuantity;
			}
			set
			{
				if ((this._iQuantity != value))
				{
					this.OniQuantityChanging(value);
					this.SendPropertyChanging();
					this._iQuantity = value;
					this.SendPropertyChanged("iQuantity");
					this.OniQuantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iPrice", DbType="Int")]
		public System.Nullable<int> iPrice
		{
			get
			{
				return this._iPrice;
			}
			set
			{
				if ((this._iPrice != value))
				{
					this.OniPriceChanging(value);
					this.SendPropertyChanging();
					this._iPrice = value;
					this.SendPropertyChanged("iPrice");
					this.OniPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbOrder_tbProductOrder", Storage="_tbOrder", ThisKey="iOrderID", OtherKey="iID", IsForeignKey=true)]
		public tbOrder tbOrder
		{
			get
			{
				return this._tbOrder.Entity;
			}
			set
			{
				tbOrder previousValue = this._tbOrder.Entity;
				if (((previousValue != value) 
							|| (this._tbOrder.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbOrder.Entity = null;
						previousValue.tbProductOrders.Remove(this);
					}
					this._tbOrder.Entity = value;
					if ((value != null))
					{
						value.tbProductOrders.Add(this);
						this._iOrderID = value.iID;
					}
					else
					{
						this._iOrderID = default(int);
					}
					this.SendPropertyChanged("tbOrder");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbProduct_tbProductOrder", Storage="_tbProduct", ThisKey="iProductID", OtherKey="iID", IsForeignKey=true)]
		public tbProduct tbProduct
		{
			get
			{
				return this._tbProduct.Entity;
			}
			set
			{
				tbProduct previousValue = this._tbProduct.Entity;
				if (((previousValue != value) 
							|| (this._tbProduct.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbProduct.Entity = null;
						previousValue.tbProductOrders.Remove(this);
					}
					this._tbProduct.Entity = value;
					if ((value != null))
					{
						value.tbProductOrders.Add(this);
						this._iProductID = value.iID;
					}
					else
					{
						this._iProductID = default(int);
					}
					this.SendPropertyChanged("tbProduct");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbProductType")]
	public partial class tbProductType : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _iID;
		
		private string _sName;
		
		private int _iProductCategory;
		
		private EntitySet<tbProduct> _tbProducts;
		
		private EntityRef<tbProductCategory> _tbProductCategory;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OniIDChanging(int value);
    partial void OniIDChanged();
    partial void OnsNameChanging(string value);
    partial void OnsNameChanged();
    partial void OniProductCategoryChanging(int value);
    partial void OniProductCategoryChanged();
    #endregion
		
		public tbProductType()
		{
			this._tbProducts = new EntitySet<tbProduct>(new Action<tbProduct>(this.attach_tbProducts), new Action<tbProduct>(this.detach_tbProducts));
			this._tbProductCategory = default(EntityRef<tbProductCategory>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int iID
		{
			get
			{
				return this._iID;
			}
			set
			{
				if ((this._iID != value))
				{
					this.OniIDChanging(value);
					this.SendPropertyChanging();
					this._iID = value;
					this.SendPropertyChanged("iID");
					this.OniIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string sName
		{
			get
			{
				return this._sName;
			}
			set
			{
				if ((this._sName != value))
				{
					this.OnsNameChanging(value);
					this.SendPropertyChanging();
					this._sName = value;
					this.SendPropertyChanged("sName");
					this.OnsNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iProductCategory", DbType="Int NOT NULL")]
		public int iProductCategory
		{
			get
			{
				return this._iProductCategory;
			}
			set
			{
				if ((this._iProductCategory != value))
				{
					if (this._tbProductCategory.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OniProductCategoryChanging(value);
					this.SendPropertyChanging();
					this._iProductCategory = value;
					this.SendPropertyChanged("iProductCategory");
					this.OniProductCategoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbProductType_tbProduct", Storage="_tbProducts", ThisKey="iID", OtherKey="iProductType")]
		public EntitySet<tbProduct> tbProducts
		{
			get
			{
				return this._tbProducts;
			}
			set
			{
				this._tbProducts.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbProductCategory_tbProductType", Storage="_tbProductCategory", ThisKey="iProductCategory", OtherKey="iID", IsForeignKey=true)]
		public tbProductCategory tbProductCategory
		{
			get
			{
				return this._tbProductCategory.Entity;
			}
			set
			{
				tbProductCategory previousValue = this._tbProductCategory.Entity;
				if (((previousValue != value) 
							|| (this._tbProductCategory.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbProductCategory.Entity = null;
						previousValue.tbProductTypes.Remove(this);
					}
					this._tbProductCategory.Entity = value;
					if ((value != null))
					{
						value.tbProductTypes.Add(this);
						this._iProductCategory = value.iID;
					}
					else
					{
						this._iProductCategory = default(int);
					}
					this.SendPropertyChanged("tbProductCategory");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbProducts(tbProduct entity)
		{
			this.SendPropertyChanging();
			entity.tbProductType = this;
		}
		
		private void detach_tbProducts(tbProduct entity)
		{
			this.SendPropertyChanging();
			entity.tbProductType = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbRole")]
	public partial class tbRole : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _iID;
		
		private string _sNamn;
		
		private EntitySet<tbUser> _tbUsers;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OniIDChanging(int value);
    partial void OniIDChanged();
    partial void OnsNamnChanging(string value);
    partial void OnsNamnChanged();
    #endregion
		
		public tbRole()
		{
			this._tbUsers = new EntitySet<tbUser>(new Action<tbUser>(this.attach_tbUsers), new Action<tbUser>(this.detach_tbUsers));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int iID
		{
			get
			{
				return this._iID;
			}
			set
			{
				if ((this._iID != value))
				{
					this.OniIDChanging(value);
					this.SendPropertyChanging();
					this._iID = value;
					this.SendPropertyChanged("iID");
					this.OniIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sNamn", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string sNamn
		{
			get
			{
				return this._sNamn;
			}
			set
			{
				if ((this._sNamn != value))
				{
					this.OnsNamnChanging(value);
					this.SendPropertyChanging();
					this._sNamn = value;
					this.SendPropertyChanged("sNamn");
					this.OnsNamnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbRole_tbUser", Storage="_tbUsers", ThisKey="iID", OtherKey="iRole")]
		public EntitySet<tbUser> tbUsers
		{
			get
			{
				return this._tbUsers;
			}
			set
			{
				this._tbUsers.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbUsers(tbUser entity)
		{
			this.SendPropertyChanging();
			entity.tbRole = this;
		}
		
		private void detach_tbUsers(tbUser entity)
		{
			this.SendPropertyChanging();
			entity.tbRole = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbShippingInfo")]
	public partial class tbShippingInfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _iID;
		
		private string _sAddress;
		
		private string _sPostalNumber;
		
		private string _sCity;
		
		private EntitySet<tbUser> _tbUsers;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OniIDChanging(int value);
    partial void OniIDChanged();
    partial void OnsAddressChanging(string value);
    partial void OnsAddressChanged();
    partial void OnsPostalNumberChanging(string value);
    partial void OnsPostalNumberChanged();
    partial void OnsCityChanging(string value);
    partial void OnsCityChanged();
    #endregion
		
		public tbShippingInfo()
		{
			this._tbUsers = new EntitySet<tbUser>(new Action<tbUser>(this.attach_tbUsers), new Action<tbUser>(this.detach_tbUsers));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int iID
		{
			get
			{
				return this._iID;
			}
			set
			{
				if ((this._iID != value))
				{
					this.OniIDChanging(value);
					this.SendPropertyChanging();
					this._iID = value;
					this.SendPropertyChanged("iID");
					this.OniIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sAddress", DbType="NVarChar(70) NOT NULL", CanBeNull=false)]
		public string sAddress
		{
			get
			{
				return this._sAddress;
			}
			set
			{
				if ((this._sAddress != value))
				{
					this.OnsAddressChanging(value);
					this.SendPropertyChanging();
					this._sAddress = value;
					this.SendPropertyChanged("sAddress");
					this.OnsAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sPostalNumber", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string sPostalNumber
		{
			get
			{
				return this._sPostalNumber;
			}
			set
			{
				if ((this._sPostalNumber != value))
				{
					this.OnsPostalNumberChanging(value);
					this.SendPropertyChanging();
					this._sPostalNumber = value;
					this.SendPropertyChanged("sPostalNumber");
					this.OnsPostalNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sCity", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string sCity
		{
			get
			{
				return this._sCity;
			}
			set
			{
				if ((this._sCity != value))
				{
					this.OnsCityChanging(value);
					this.SendPropertyChanging();
					this._sCity = value;
					this.SendPropertyChanged("sCity");
					this.OnsCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbShippingInfo_tbUser", Storage="_tbUsers", ThisKey="iID", OtherKey="iShippingInfo")]
		public EntitySet<tbUser> tbUsers
		{
			get
			{
				return this._tbUsers;
			}
			set
			{
				this._tbUsers.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbUsers(tbUser entity)
		{
			this.SendPropertyChanging();
			entity.tbShippingInfo = this;
		}
		
		private void detach_tbUsers(tbUser entity)
		{
			this.SendPropertyChanging();
			entity.tbShippingInfo = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbStatus")]
	public partial class tbStatus : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _iID;
		
		private string _sOrderStatus;
		
		private EntitySet<tbOrder> _tbOrders;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OniIDChanging(int value);
    partial void OniIDChanged();
    partial void OnsOrderStatusChanging(string value);
    partial void OnsOrderStatusChanged();
    #endregion
		
		public tbStatus()
		{
			this._tbOrders = new EntitySet<tbOrder>(new Action<tbOrder>(this.attach_tbOrders), new Action<tbOrder>(this.detach_tbOrders));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int iID
		{
			get
			{
				return this._iID;
			}
			set
			{
				if ((this._iID != value))
				{
					this.OniIDChanging(value);
					this.SendPropertyChanging();
					this._iID = value;
					this.SendPropertyChanged("iID");
					this.OniIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sOrderStatus", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string sOrderStatus
		{
			get
			{
				return this._sOrderStatus;
			}
			set
			{
				if ((this._sOrderStatus != value))
				{
					this.OnsOrderStatusChanging(value);
					this.SendPropertyChanging();
					this._sOrderStatus = value;
					this.SendPropertyChanged("sOrderStatus");
					this.OnsOrderStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbStatus_tbOrder", Storage="_tbOrders", ThisKey="iID", OtherKey="iStatus")]
		public EntitySet<tbOrder> tbOrders
		{
			get
			{
				return this._tbOrders;
			}
			set
			{
				this._tbOrders.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbOrders(tbOrder entity)
		{
			this.SendPropertyChanging();
			entity.tbStatus = this;
		}
		
		private void detach_tbOrders(tbOrder entity)
		{
			this.SendPropertyChanging();
			entity.tbStatus = null;
		}
	}
}
#pragma warning restore 1591
